### PR TITLE
fixes #4; bumps joi version

### LINKED ISSUE #4: Upgrade to Joi 6.x.x

### PR DESCRIPTION
**Pull request by mgartner**
@lob/api-engineering-team

### CODE REVIEW

**Comment by leore** [comment]
LGTM @mgartner living dangerously

**Comment by leore** [comment]
@lob/api-engineering-team why are there 2 Travis builds

**Comment by pon** [comment]
It's a Travis - aggregates the initial push of the branch and creation of the PR

**Comment by pon** [comment]
LGTM

**Pull request merged**
