### PR TITLE
Remove Serializer

### PR DESCRIPTION
**Pull request by pon**
## What

- Updated README.md with new documentation
- Updated linters to 120 characters
- Removed `serializer` pattern - now it is required to use the `serialize`method

## Why

Joi was meant for validation not formatting - we have found it adds undue complexity to what should be a simple task

@elnaz @mgartner @robinjoseph08 @brianseitel

### CODE REVIEW

**Comment by pon** [comment]
Not sure why coverage is complaining - https://coveralls.io/builds/3152952

**Comment by pon** [comment]
Coveralls working now...

**Comment by robinjoseph08** [comment]
LGTM

**Comment by mgartner** [comment]
LGTM

**Pull request merged**
