### PR TITLE
feat(context): set request as context for serializer

### PR DESCRIPTION
**Pull request by pon**
@lob/api-engineering-team

### CODE REVIEW

**Comment by mgartner** [comment]
LGTM. Might want to add something to the README to explain this feature

**Comment by leore** [comment]
Please add to README and re ping

**Comment by mgartner** [comment]
@lob/api-engineering-team updated README

Does it make sense to bump Joi to 6.x.x here too?

**Comment by pon** [comment]
Yeah - I would bump in a separate PR though

**Comment by pon** [comment]
LGTM

**Comment by leore** [comment]
LGTM

**Pull request merged**
